title: "Frank Kruse"
author: "Frank Kruse"
email: "frank@woopec.net"

description: "Programming is fun. With clean code, the fun lasts longer." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# minima:
#  social_links:
#    github: FrankFK
# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out

minima:
  social_links:
    mastodon:
      - username: FrankKruse
        instance: fosstodon.org
    github: FrankFK

#twitter_username: "twitteruser"
github_username: "FrankFK"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

show_excerpts: true

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

# 02.04.2023: Diese url wird benoetigt, damit der jekyll-sitemap Generator eine sitemap.xml mit absoluten URLs generiert. Google moechte das so haben.
url: "https://github.com/FrankFK/FrankFK.github.io"
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  enabled: false
  strip_title: true
  collections: true

header_pages:
  - blog.md
  - about.md


defaults:
  - 
    scope:
      path: ""
      type: post
    values:
      tags: Other
  - 
    scope:
      path: ""
    values:
      image:
        path: /assets/images/LogoWithTextForLinkPreview.png
        height: 405
        width: 650

